name: .NET Core CI (Continuous Integration) #Definimos o nome do nosso Workflow

on:
  push:
    branches:
      - develop #Definimos o gatilho para nossa automação

jobs:

  CreatePullRequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pull request #Etapa de criação do pull request usando o cli do github
        run: gh pr create -B main -H develop --title 'Merge Develop into Main' --body 'Created automatic Pull Request by Github action.'
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}