name: .NET Core CI (Continuous Integration) #Definimos o nome do nosso Workflow

on:
  push:
    branches:
      - develop #Definimos o gatilho para nossa automação

jobs:

  BuildAndTestApplication: #Criamos o job de build testes
    runs-on: ubuntu-latest #Definimos o container/virtualização
    
    steps:
      - name: Checkout code #Etapa de checkout do repositório
        uses: actions/checkout@v3

      - name: Restore dependencies #Etapa do restore
        run: dotnet restore
      
      - name: Build application #Etapa do build
        run: dotnet build --no-restore

      - name: Test application #Etapa do teste
        run: dotnet test --no-build --verbosity normal

  CreatePullRequest:
    needs: BuildAndTestApplication
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pull request #Etapa de criação do pull request usando o cli do github
        run: gh pr create -B main -H develop --title 'Merge Develop into Main' --body 'Created automatic Pull Request by Github action.'
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}